name: IntelSphereBot

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'   # يُعيد التشغيل يومياً
  workflow_dispatch:      # يتيح لك التشغيل اليدوي

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 0    # لا يُوقفه بعد دقائق
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python bot.py
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
